grails-app/domain/studentgradesifgalphagrails/Student.groovy
package studentgradesifgalphagrails

class Student {

    String fullName
    String gender
    Integer birthYear
    String address
    String city
    String country
    String telNum
    String email
    String proSituation
    String success
    String mode
    String photo // TODO - refactor

    static constraints = {
        gender maxSize: 1
    }

    static hasMany = [letters: Letter, exams: Exam]
    static hasOne = [initalFormation: InitialFormation, promotion: Promotion, studyPeriod: StudyPeriod]
}

grails-app/controllers/studentgradesifgalphagrails/StudentController.groovy
package studentgradesifgalphagrails

import grails.transaction.Transactional

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class StudentController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Student.list(params), model: [studentInstanceCount: Student.count()]
    }

    def show(Student studentInstance) {
        respond studentInstance
    }

    def create() {
        respond new Student(params)
    }

    @Transactional
    def save(Student studentInstance) {
        if (studentInstance == null) {
            notFound()
            return
        }

        if (studentInstance.hasErrors()) {
            respond studentInstance.errors, view: 'create'
            return
        }

        studentInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'student.label', default: 'Student'), studentInstance.id])
                redirect studentInstance
            }
            '*' { respond studentInstance, [status: CREATED] }
        }
    }

    def edit(Student studentInstance) {
        respond studentInstance
    }

    @Transactional
    def update(Student studentInstance) {
        if (studentInstance == null) {
            notFound()
            return
        }

        if (studentInstance.hasErrors()) {
            respond studentInstance.errors, view: 'edit'
            return
        }

        studentInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Student.label', default: 'Student'), studentInstance.id])
                redirect studentInstance
            }
            '*' { respond studentInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Student studentInstance) {

        if (studentInstance == null) {
            notFound()
            return
        }

        studentInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Student.label', default: 'Student'), studentInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'student.label', default: 'Student'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/student/_form.gsp
<%@ page import="studentgradesifgalphagrails.Student" %>



<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'gender', 'error')} required">
    <label for="gender">
        <g:message code="student.gender.label" default="Gender"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="gender" maxlength="1" required="" value="${studentInstance?.gender}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'address', 'error')} required">
    <label for="address">
        <g:message code="student.address.label" default="Address"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="address" required="" value="${studentInstance?.address}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'birthYear', 'error')} required">
    <label for="birthYear">
        <g:message code="student.birthYear.label" default="Birth Year"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="birthYear" type="number" value="${studentInstance.birthYear}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'city', 'error')} required">
    <label for="city">
        <g:message code="student.city.label" default="City"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="city" required="" value="${studentInstance?.city}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'country', 'error')} required">
    <label for="country">
        <g:message code="student.country.label" default="Country"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="country" required="" value="${studentInstance?.country}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'email', 'error')} required">
    <label for="email">
        <g:message code="student.email.label" default="Email"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="email" required="" value="${studentInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'exams', 'error')} ">
    <label for="exams">
        <g:message code="student.exams.label" default="Exams"/>

    </label>

    <ul class="one-to-many">
        <g:each in="${studentInstance?.exams ?}" var="e">
            <li><g:link controller="exam" action="show" id="${e.id}">${e?.encodeAsHTML()}</g:link></li>
        </g:each>
        <li class="add">
            <g:link controller="exam" action="create"
                    params="['student.id': studentInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'exam.label', default: 'Exam')])}</g:link>
        </li>
    </ul>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'fullName', 'error')} required">
    <label for="fullName">
        <g:message code="student.fullName.label" default="Full Name"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="fullName" required="" value="${studentInstance?.fullName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'initalFormation', 'error')} required">
    <label for="initalFormation">
        <g:message code="student.initalFormation.label" default="Inital Formation"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="initalFormation" name="initalFormation.id"
              from="${studentgradesifgalphagrails.InitialFormation.list()}" optionKey="id" required=""
              value="${studentInstance?.initalFormation?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'letters', 'error')} ">
    <label for="letters">
        <g:message code="student.letters.label" default="Letters"/>

    </label>

    <ul class="one-to-many">
        <g:each in="${studentInstance?.letters ?}" var="l">
            <li><g:link controller="letter" action="show" id="${l.id}">${l?.encodeAsHTML()}</g:link></li>
        </g:each>
        <li class="add">
            <g:link controller="letter" action="create"
                    params="['student.id': studentInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'letter.label', default: 'Letter')])}</g:link>
        </li>
    </ul>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'mode', 'error')} required">
    <label for="mode">
        <g:message code="student.mode.label" default="Mode"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="mode" required="" value="${studentInstance?.mode}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'photo', 'error')} required">
    <label for="photo">
        <g:message code="student.photo.label" default="Photo"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="photo" required="" value="${studentInstance?.photo}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'proSituation', 'error')} required">
    <label for="proSituation">
        <g:message code="student.proSituation.label" default="Pro Situation"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="proSituation" required="" value="${studentInstance?.proSituation}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'promotion', 'error')} required">
    <label for="promotion">
        <g:message code="student.promotion.label" default="Promotion"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="promotion" name="promotion.id" from="${studentgradesifgalphagrails.Promotion.list()}" optionKey="id"
              required="" value="${studentInstance?.promotion?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'studyPeriod', 'error')} required">
    <label for="studyPeriod">
        <g:message code="student.studyPeriod.label" default="Study Period"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="studyPeriod" name="studyPeriod.id" from="${studentgradesifgalphagrails.StudyPeriod.list()}"
              optionKey="id" required="" value="${studentInstance?.studyPeriod?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'success', 'error')} required">
    <label for="success">
        <g:message code="student.success.label" default="Success"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="success" required="" value="${studentInstance?.success}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: studentInstance, field: 'telNum', 'error')} required">
    <label for="telNum">
        <g:message code="student.telNum.label" default="Tel Num"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="telNum" required="" value="${studentInstance?.telNum}"/>

</div>

grails-app/views/student/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-student" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-student" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${studentInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${studentInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: studentInstance, action: 'save']">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/student/edit.gsp
<%@ page import="studentgradesifgalphagrails.Student" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-student" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                              default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-student" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${studentInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${studentInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: studentInstance, action: 'update']" method="PUT">
        <g:hiddenField name="version" value="${studentInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/student/index.gsp
<%@ page import="studentgradesifgalphagrails.Student" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-student" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                              default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-student" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="gender" title="${message(code: 'student.gender.label', default: 'Gender')}"/>

            <g:sortableColumn property="address" title="${message(code: 'student.address.label', default: 'Address')}"/>

            <g:sortableColumn property="birthYear"
                              title="${message(code: 'student.birthYear.label', default: 'Birth Year')}"/>

            <g:sortableColumn property="city" title="${message(code: 'student.city.label', default: 'City')}"/>

            <g:sortableColumn property="country" title="${message(code: 'student.country.label', default: 'Country')}"/>

            <g:sortableColumn property="email" title="${message(code: 'student.email.label', default: 'Email')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${studentInstanceList}" status="i" var="studentInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${studentInstance.id}">${fieldValue(bean: studentInstance, field: "gender")}</g:link></td>

                <td>${fieldValue(bean: studentInstance, field: "address")}</td>

                <td>${fieldValue(bean: studentInstance, field: "birthYear")}</td>

                <td>${fieldValue(bean: studentInstance, field: "city")}</td>

                <td>${fieldValue(bean: studentInstance, field: "country")}</td>

                <td>${fieldValue(bean: studentInstance, field: "email")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${studentInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/student/show.gsp
<%@ page import="studentgradesifgalphagrails.Student" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'student.label', default: 'Student')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-student" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                              default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-student" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list student">

        <g:if test="${studentInstance?.gender}">
            <li class="fieldcontain">
                <span id="gender-label" class="property-label"><g:message code="student.gender.label"
                                                                          default="Gender"/></span>

                <span class="property-value" aria-labelledby="gender-label"><g:fieldValue bean="${studentInstance}"
                                                                                          field="gender"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.address}">
            <li class="fieldcontain">
                <span id="address-label" class="property-label"><g:message code="student.address.label"
                                                                           default="Address"/></span>

                <span class="property-value" aria-labelledby="address-label"><g:fieldValue bean="${studentInstance}"
                                                                                           field="address"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.birthYear}">
            <li class="fieldcontain">
                <span id="birthYear-label" class="property-label"><g:message code="student.birthYear.label"
                                                                             default="Birth Year"/></span>

                <span class="property-value" aria-labelledby="birthYear-label"><g:fieldValue bean="${studentInstance}"
                                                                                             field="birthYear"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.city}">
            <li class="fieldcontain">
                <span id="city-label" class="property-label"><g:message code="student.city.label"
                                                                        default="City"/></span>

                <span class="property-value" aria-labelledby="city-label"><g:fieldValue bean="${studentInstance}"
                                                                                        field="city"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.country}">
            <li class="fieldcontain">
                <span id="country-label" class="property-label"><g:message code="student.country.label"
                                                                           default="Country"/></span>

                <span class="property-value" aria-labelledby="country-label"><g:fieldValue bean="${studentInstance}"
                                                                                           field="country"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.email}">
            <li class="fieldcontain">
                <span id="email-label" class="property-label"><g:message code="student.email.label"
                                                                         default="Email"/></span>

                <span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${studentInstance}"
                                                                                         field="email"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.exams}">
            <li class="fieldcontain">
                <span id="exams-label" class="property-label"><g:message code="student.exams.label"
                                                                         default="Exams"/></span>

                <g:each in="${studentInstance.exams}" var="e">
                    <span class="property-value" aria-labelledby="exams-label"><g:link controller="exam" action="show"
                                                                                       id="${e.id}">${e?.encodeAsHTML()}</g:link></span>
                </g:each>

            </li>
        </g:if>

        <g:if test="${studentInstance?.fullName}">
            <li class="fieldcontain">
                <span id="fullName-label" class="property-label"><g:message code="student.fullName.label"
                                                                            default="Full Name"/></span>

                <span class="property-value" aria-labelledby="fullName-label"><g:fieldValue bean="${studentInstance}"
                                                                                            field="fullName"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.initalFormation}">
            <li class="fieldcontain">
                <span id="initalFormation-label" class="property-label"><g:message code="student.initalFormation.label"
                                                                                   default="Inital Formation"/></span>

                <span class="property-value" aria-labelledby="initalFormation-label"><g:link
                        controller="initialFormation" action="show"
                        id="${studentInstance?.initalFormation?.id}">${studentInstance?.initalFormation?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.letters}">
            <li class="fieldcontain">
                <span id="letters-label" class="property-label"><g:message code="student.letters.label"
                                                                           default="Letters"/></span>

                <g:each in="${studentInstance.letters}" var="l">
                    <span class="property-value" aria-labelledby="letters-label"><g:link controller="letter"
                                                                                         action="show"
                                                                                         id="${l.id}">${l?.encodeAsHTML()}</g:link></span>
                </g:each>

            </li>
        </g:if>

        <g:if test="${studentInstance?.mode}">
            <li class="fieldcontain">
                <span id="mode-label" class="property-label"><g:message code="student.mode.label"
                                                                        default="Mode"/></span>

                <span class="property-value" aria-labelledby="mode-label"><g:fieldValue bean="${studentInstance}"
                                                                                        field="mode"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.photo}">
            <li class="fieldcontain">
                <span id="photo-label" class="property-label"><g:message code="student.photo.label"
                                                                         default="Photo"/></span>

                <span class="property-value" aria-labelledby="photo-label"><g:fieldValue bean="${studentInstance}"
                                                                                         field="photo"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.proSituation}">
            <li class="fieldcontain">
                <span id="proSituation-label" class="property-label"><g:message code="student.proSituation.label"
                                                                                default="Pro Situation"/></span>

                <span class="property-value" aria-labelledby="proSituation-label"><g:fieldValue
                        bean="${studentInstance}" field="proSituation"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.promotion}">
            <li class="fieldcontain">
                <span id="promotion-label" class="property-label"><g:message code="student.promotion.label"
                                                                             default="Promotion"/></span>

                <span class="property-value" aria-labelledby="promotion-label"><g:link controller="promotion"
                                                                                       action="show"
                                                                                       id="${studentInstance?.promotion?.id}">${studentInstance?.promotion?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.studyPeriod}">
            <li class="fieldcontain">
                <span id="studyPeriod-label" class="property-label"><g:message code="student.studyPeriod.label"
                                                                               default="Study Period"/></span>

                <span class="property-value" aria-labelledby="studyPeriod-label"><g:link controller="studyPeriod"
                                                                                         action="show"
                                                                                         id="${studentInstance?.studyPeriod?.id}">${studentInstance?.studyPeriod?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.success}">
            <li class="fieldcontain">
                <span id="success-label" class="property-label"><g:message code="student.success.label"
                                                                           default="Success"/></span>

                <span class="property-value" aria-labelledby="success-label"><g:fieldValue bean="${studentInstance}"
                                                                                           field="success"/></span>

            </li>
        </g:if>

        <g:if test="${studentInstance?.telNum}">
            <li class="fieldcontain">
                <span id="telNum-label" class="property-label"><g:message code="student.telNum.label"
                                                                          default="Tel Num"/></span>

                <span class="property-value" aria-labelledby="telNum-label"><g:fieldValue bean="${studentInstance}"
                                                                                          field="telNum"/></span>

            </li>
        </g:if>

    </ol>
    <g:form url="[resource: studentInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${studentInstance}"><g:message code="default.button.edit.label"
                                                                                        default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>