grails-app/domain/studentgradesifgalphagrails/Professor.groovy
package studentgradesifgalphagrails

class Professor {

    String fullName
    String establishment
    String email
    String telNum
    Integer teachingStartYear
    Integer teachingEndYear

    static constraints = {
        teachingEndYear nullable: true
    }

    static hasMany = [exams: Exam]
}

grails-app/controllers/studentgradesifgalphagrails/ProfessorController.groovy
package studentgradesifgalphagrails

import grails.transaction.Transactional

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class ProfessorController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Professor.list(params), model: [professorInstanceCount: Professor.count()]
    }

    def show(Professor professorInstance) {
        respond professorInstance
    }

    def create() {
        respond new Professor(params)
    }

    @Transactional
    def save(Professor professorInstance) {
        if (professorInstance == null) {
            notFound()
            return
        }

        if (professorInstance.hasErrors()) {
            respond professorInstance.errors, view: 'create'
            return
        }

        professorInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'professor.label', default: 'Professor'), professorInstance.id])
                redirect professorInstance
            }
            '*' { respond professorInstance, [status: CREATED] }
        }
    }

    def edit(Professor professorInstance) {
        respond professorInstance
    }

    @Transactional
    def update(Professor professorInstance) {
        if (professorInstance == null) {
            notFound()
            return
        }

        if (professorInstance.hasErrors()) {
            respond professorInstance.errors, view: 'edit'
            return
        }

        professorInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Professor.label', default: 'Professor'), professorInstance.id])
                redirect professorInstance
            }
            '*' { respond professorInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Professor professorInstance) {

        if (professorInstance == null) {
            notFound()
            return
        }

        professorInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Professor.label', default: 'Professor'), professorInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'professor.label', default: 'Professor'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/professor/_form.gsp
<%@ page import="studentgradesifgalphagrails.Professor" %>



<div class="fieldcontain ${hasErrors(bean: professorInstance, field: 'teachingEndYear', 'error')} ">
    <label for="teachingEndYear">
        <g:message code="professor.teachingEndYear.label" default="Teaching End Year"/>

    </label>
    <g:field name="teachingEndYear" type="number" value="${professorInstance.teachingEndYear}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: professorInstance, field: 'email', 'error')} required">
    <label for="email">
        <g:message code="professor.email.label" default="Email"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="email" required="" value="${professorInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: professorInstance, field: 'establishment', 'error')} required">
    <label for="establishment">
        <g:message code="professor.establishment.label" default="Establishment"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="establishment" required="" value="${professorInstance?.establishment}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: professorInstance, field: 'exams', 'error')} ">
    <label for="exams">
        <g:message code="professor.exams.label" default="Exams"/>

    </label>

    <ul class="one-to-many">
        <g:each in="${professorInstance?.exams ?}" var="e">
            <li><g:link controller="exam" action="show" id="${e.id}">${e?.encodeAsHTML()}</g:link></li>
        </g:each>
        <li class="add">
            <g:link controller="exam" action="create"
                    params="['professor.id': professorInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'exam.label', default: 'Exam')])}</g:link>
        </li>
    </ul>

</div>

<div class="fieldcontain ${hasErrors(bean: professorInstance, field: 'fullName', 'error')} required">
    <label for="fullName">
        <g:message code="professor.fullName.label" default="Full Name"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="fullName" required="" value="${professorInstance?.fullName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: professorInstance, field: 'teachingStartYear', 'error')} required">
    <label for="teachingStartYear">
        <g:message code="professor.teachingStartYear.label" default="Teaching Start Year"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="teachingStartYear" type="number" value="${professorInstance.teachingStartYear}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: professorInstance, field: 'telNum', 'error')} required">
    <label for="telNum">
        <g:message code="professor.telNum.label" default="Tel Num"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="telNum" required="" value="${professorInstance?.telNum}"/>

</div>

grails-app/views/professor/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'professor.label', default: 'Professor')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-professor" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-professor" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${professorInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${professorInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: professorInstance, action: 'save']">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/professor/edit.gsp
<%@ page import="studentgradesifgalphagrails.Professor" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'professor.label', default: 'Professor')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-professor" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-professor" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${professorInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${professorInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: professorInstance, action: 'update']" method="PUT">
        <g:hiddenField name="version" value="${professorInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/professor/index.gsp
<%@ page import="studentgradesifgalphagrails.Professor" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'professor.label', default: 'Professor')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-professor" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-professor" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="teachingEndYear"
                              title="${message(code: 'professor.teachingEndYear.label', default: 'Teaching End Year')}"/>

            <g:sortableColumn property="email" title="${message(code: 'professor.email.label', default: 'Email')}"/>

            <g:sortableColumn property="establishment"
                              title="${message(code: 'professor.establishment.label', default: 'Establishment')}"/>

            <g:sortableColumn property="fullName"
                              title="${message(code: 'professor.fullName.label', default: 'Full Name')}"/>

            <g:sortableColumn property="teachingStartYear"
                              title="${message(code: 'professor.teachingStartYear.label', default: 'Teaching Start Year')}"/>

            <g:sortableColumn property="telNum" title="${message(code: 'professor.telNum.label', default: 'Tel Num')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${professorInstanceList}" status="i" var="professorInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${professorInstance.id}">${fieldValue(bean: professorInstance, field: "teachingEndYear")}</g:link></td>

                <td>${fieldValue(bean: professorInstance, field: "email")}</td>

                <td>${fieldValue(bean: professorInstance, field: "establishment")}</td>

                <td>${fieldValue(bean: professorInstance, field: "fullName")}</td>

                <td>${fieldValue(bean: professorInstance, field: "teachingStartYear")}</td>

                <td>${fieldValue(bean: professorInstance, field: "telNum")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${professorInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/professor/show.gsp
<%@ page import="studentgradesifgalphagrails.Professor" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'professor.label', default: 'Professor')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-professor" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-professor" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list professor">

        <g:if test="${professorInstance?.teachingEndYear}">
            <li class="fieldcontain">
                <span id="teachingEndYear-label" class="property-label"><g:message
                        code="professor.teachingEndYear.label" default="Teaching End Year"/></span>

                <span class="property-value" aria-labelledby="teachingEndYear-label"><g:fieldValue
                        bean="${professorInstance}" field="teachingEndYear"/></span>

            </li>
        </g:if>

        <g:if test="${professorInstance?.email}">
            <li class="fieldcontain">
                <span id="email-label" class="property-label"><g:message code="professor.email.label"
                                                                         default="Email"/></span>

                <span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${professorInstance}"
                                                                                         field="email"/></span>

            </li>
        </g:if>

        <g:if test="${professorInstance?.establishment}">
            <li class="fieldcontain">
                <span id="establishment-label" class="property-label"><g:message code="professor.establishment.label"
                                                                                 default="Establishment"/></span>

                <span class="property-value" aria-labelledby="establishment-label"><g:fieldValue
                        bean="${professorInstance}" field="establishment"/></span>

            </li>
        </g:if>

        <g:if test="${professorInstance?.exams}">
            <li class="fieldcontain">
                <span id="exams-label" class="property-label"><g:message code="professor.exams.label"
                                                                         default="Exams"/></span>

                <g:each in="${professorInstance.exams}" var="e">
                    <span class="property-value" aria-labelledby="exams-label"><g:link controller="exam" action="show"
                                                                                       id="${e.id}">${e?.encodeAsHTML()}</g:link></span>
                </g:each>

            </li>
        </g:if>

        <g:if test="${professorInstance?.fullName}">
            <li class="fieldcontain">
                <span id="fullName-label" class="property-label"><g:message code="professor.fullName.label"
                                                                            default="Full Name"/></span>

                <span class="property-value" aria-labelledby="fullName-label"><g:fieldValue bean="${professorInstance}"
                                                                                            field="fullName"/></span>

            </li>
        </g:if>

        <g:if test="${professorInstance?.teachingStartYear}">
            <li class="fieldcontain">
                <span id="teachingStartYear-label" class="property-label"><g:message
                        code="professor.teachingStartYear.label" default="Teaching Start Year"/></span>

                <span class="property-value" aria-labelledby="teachingStartYear-label"><g:fieldValue
                        bean="${professorInstance}" field="teachingStartYear"/></span>

            </li>
        </g:if>

        <g:if test="${professorInstance?.telNum}">
            <li class="fieldcontain">
                <span id="telNum-label" class="property-label"><g:message code="professor.telNum.label"
                                                                          default="Tel Num"/></span>

                <span class="property-value" aria-labelledby="telNum-label"><g:fieldValue bean="${professorInstance}"
                                                                                          field="telNum"/></span>

            </li>
        </g:if>

    </ol>
    <g:form url="[resource: professorInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${professorInstance}"><g:message
                    code="default.button.edit.label" default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>