grails-app/domain/studentgradesifgalphagrails/Promotion.groovy
package studentgradesifgalphagrails

class Promotion {

    String promotion

    static constraints = {
    }

    static hasMany = [students: Student]
}

grails-app/controllers/studentgradesifgalphagrails/PromotionController.groovy
package studentgradesifgalphagrails

import grails.transaction.Transactional

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class PromotionController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Promotion.list(params), model: [promotionInstanceCount: Promotion.count()]
    }

    def show(Promotion promotionInstance) {
        respond promotionInstance
    }

    def create() {
        respond new Promotion(params)
    }

    @Transactional
    def save(Promotion promotionInstance) {
        if (promotionInstance == null) {
            notFound()
            return
        }

        if (promotionInstance.hasErrors()) {
            respond promotionInstance.errors, view: 'create'
            return
        }

        promotionInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'promotion.label', default: 'Promotion'), promotionInstance.id])
                redirect promotionInstance
            }
            '*' { respond promotionInstance, [status: CREATED] }
        }
    }

    def edit(Promotion promotionInstance) {
        respond promotionInstance
    }

    @Transactional
    def update(Promotion promotionInstance) {
        if (promotionInstance == null) {
            notFound()
            return
        }

        if (promotionInstance.hasErrors()) {
            respond promotionInstance.errors, view: 'edit'
            return
        }

        promotionInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Promotion.label', default: 'Promotion'), promotionInstance.id])
                redirect promotionInstance
            }
            '*' { respond promotionInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Promotion promotionInstance) {

        if (promotionInstance == null) {
            notFound()
            return
        }

        promotionInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Promotion.label', default: 'Promotion'), promotionInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'promotion.label', default: 'Promotion'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/promotion/_form.gsp
<%@ page import="studentgradesifgalphagrails.Promotion" %>



<div class="fieldcontain ${hasErrors(bean: promotionInstance, field: 'promotion', 'error')} required">
    <label for="promotion">
        <g:message code="promotion.promotion.label" default="Promotion"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="promotion" required="" value="${promotionInstance?.promotion}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: promotionInstance, field: 'students', 'error')} ">
    <label for="students">
        <g:message code="promotion.students.label" default="Students"/>

    </label>

    <ul class="one-to-many">
        <g:each in="${promotionInstance?.students ?}" var="s">
            <li><g:link controller="student" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></li>
        </g:each>
        <li class="add">
            <g:link controller="student" action="create"
                    params="['promotion.id': promotionInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'student.label', default: 'Student')])}</g:link>
        </li>
    </ul>

</div>

grails-app/views/promotion/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'promotion.label', default: 'Promotion')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-promotion" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-promotion" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${promotionInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${promotionInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: promotionInstance, action: 'save']">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/promotion/edit.gsp
<%@ page import="studentgradesifgalphagrails.Promotion" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'promotion.label', default: 'Promotion')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-promotion" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-promotion" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${promotionInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${promotionInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: promotionInstance, action: 'update']" method="PUT">
        <g:hiddenField name="version" value="${promotionInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/promotion/index.gsp
<%@ page import="studentgradesifgalphagrails.Promotion" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'promotion.label', default: 'Promotion')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-promotion" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-promotion" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="promotion"
                              title="${message(code: 'promotion.promotion.label', default: 'Promotion')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${promotionInstanceList}" status="i" var="promotionInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${promotionInstance.id}">${fieldValue(bean: promotionInstance, field: "promotion")}</g:link></td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${promotionInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/promotion/show.gsp
<%@ page import="studentgradesifgalphagrails.Promotion" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'promotion.label', default: 'Promotion')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-promotion" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-promotion" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list promotion">

        <g:if test="${promotionInstance?.promotion}">
            <li class="fieldcontain">
                <span id="promotion-label" class="property-label"><g:message code="promotion.promotion.label"
                                                                             default="Promotion"/></span>

                <span class="property-value" aria-labelledby="promotion-label"><g:fieldValue bean="${promotionInstance}"
                                                                                             field="promotion"/></span>

            </li>
        </g:if>

        <g:if test="${promotionInstance?.students}">
            <li class="fieldcontain">
                <span id="students-label" class="property-label"><g:message code="promotion.students.label"
                                                                            default="Students"/></span>

                <g:each in="${promotionInstance.students}" var="s">
                    <span class="property-value" aria-labelledby="students-label"><g:link controller="student"
                                                                                          action="show"
                                                                                          id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
                </g:each>

            </li>
        </g:if>

    </ol>
    <g:form url="[resource: promotionInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${promotionInstance}"><g:message
                    code="default.button.edit.label" default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>