grails-app/domain/studentgradesifgalphagrails/InitialFormation.groovy
package studentgradesifgalphagrails

class InitialFormation {

    String initialFormation

    static constraints = {
    }

    static hasMany = [students: Student]
}

grails-app/controllers/studentgradesifgalphagrails/InitialFormationController.groovy
package studentgradesifgalphagrails

import grails.transaction.Transactional

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class InitialFormationController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond InitialFormation.list(params), model: [initialFormationInstanceCount: InitialFormation.count()]
    }

    def show(InitialFormation initialFormationInstance) {
        respond initialFormationInstance
    }

    def create() {
        respond new InitialFormation(params)
    }

    @Transactional
    def save(InitialFormation initialFormationInstance) {
        if (initialFormationInstance == null) {
            notFound()
            return
        }

        if (initialFormationInstance.hasErrors()) {
            respond initialFormationInstance.errors, view: 'create'
            return
        }

        initialFormationInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'initialFormation.label', default: 'InitialFormation'), initialFormationInstance.id])
                redirect initialFormationInstance
            }
            '*' { respond initialFormationInstance, [status: CREATED] }
        }
    }

    def edit(InitialFormation initialFormationInstance) {
        respond initialFormationInstance
    }

    @Transactional
    def update(InitialFormation initialFormationInstance) {
        if (initialFormationInstance == null) {
            notFound()
            return
        }

        if (initialFormationInstance.hasErrors()) {
            respond initialFormationInstance.errors, view: 'edit'
            return
        }

        initialFormationInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'InitialFormation.label', default: 'InitialFormation'), initialFormationInstance.id])
                redirect initialFormationInstance
            }
            '*' { respond initialFormationInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(InitialFormation initialFormationInstance) {

        if (initialFormationInstance == null) {
            notFound()
            return
        }

        initialFormationInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'InitialFormation.label', default: 'InitialFormation'), initialFormationInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'initialFormation.label', default: 'InitialFormation'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/initialFormation/_form.gsp
<%@ page import="studentgradesifgalphagrails.InitialFormation" %>



<div class="fieldcontain ${hasErrors(bean: initialFormationInstance, field: 'initialFormation', 'error')} required">
    <label for="initialFormation">
        <g:message code="initialFormation.initialFormation.label" default="Initial Formation"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="initialFormation" required="" value="${initialFormationInstance?.initialFormation}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: initialFormationInstance, field: 'students', 'error')} ">
    <label for="students">
        <g:message code="initialFormation.students.label" default="Students"/>

    </label>

    <ul class="one-to-many">
        <g:each in="${initialFormationInstance?.students ?}" var="s">
            <li><g:link controller="student" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></li>
        </g:each>
        <li class="add">
            <g:link controller="student" action="create"
                    params="['initialFormation.id': initialFormationInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'student.label', default: 'Student')])}</g:link>
        </li>
    </ul>

</div>

grails-app/views/initialFormation/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'initialFormation.label', default: 'InitialFormation')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-initialFormation" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                         default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-initialFormation" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${initialFormationInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${initialFormationInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: initialFormationInstance, action: 'save']">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/initialFormation/edit.gsp
<%@ page import="studentgradesifgalphagrails.InitialFormation" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'initialFormation.label', default: 'InitialFormation')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-initialFormation" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                       default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-initialFormation" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${initialFormationInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${initialFormationInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: initialFormationInstance, action: 'update']" method="PUT">
        <g:hiddenField name="version" value="${initialFormationInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/initialFormation/index.gsp
<%@ page import="studentgradesifgalphagrails.InitialFormation" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'initialFormation.label', default: 'InitialFormation')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-initialFormation" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                       default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-initialFormation" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="initialFormation"
                              title="${message(code: 'initialFormation.initialFormation.label', default: 'Initial Formation')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${initialFormationInstanceList}" status="i" var="initialFormationInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${initialFormationInstance.id}">${fieldValue(bean: initialFormationInstance, field: "initialFormation")}</g:link></td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${initialFormationInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/initialFormation/show.gsp
<%@ page import="studentgradesifgalphagrails.InitialFormation" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'initialFormation.label', default: 'InitialFormation')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-initialFormation" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                       default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-initialFormation" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list initialFormation">

        <g:if test="${initialFormationInstance?.initialFormation}">
            <li class="fieldcontain">
                <span id="initialFormation-label" class="property-label"><g:message
                        code="initialFormation.initialFormation.label" default="Initial Formation"/></span>

                <span class="property-value" aria-labelledby="initialFormation-label"><g:fieldValue
                        bean="${initialFormationInstance}" field="initialFormation"/></span>

            </li>
        </g:if>

        <g:if test="${initialFormationInstance?.students}">
            <li class="fieldcontain">
                <span id="students-label" class="property-label"><g:message code="initialFormation.students.label"
                                                                            default="Students"/></span>

                <g:each in="${initialFormationInstance.students}" var="s">
                    <span class="property-value" aria-labelledby="students-label"><g:link controller="student"
                                                                                          action="show"
                                                                                          id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
                </g:each>

            </li>
        </g:if>

    </ol>
    <g:form url="[resource: initialFormationInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${initialFormationInstance}"><g:message
                    code="default.button.edit.label" default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>